### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by sharansudheer** [sharansudheer/nextjs-reactjs-patchwork#12]
#11 in that, there's a Run Time error in the browser
at Home
    at MyApp (webpack-internal:///./pages/_app.js:23:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20742)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23635)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:70:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:216:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:403:27)
window.console.error @ next-dev.js:20

I need to dig on the issue

**Comment by sharansudheer** [comment]
Closing the error, as it does not appear in Deployment, it only appears in Run Dev
